# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "box" do |box|
    box.vm.box = "hashicorp/precise32"
    box.vm.hostname = "lab1-box"
    box.vm.network "private_network", ip: "192.168.255.11"
    box.vm.provider "virtualbox" do |virtualbox|
        # Enable promiscuous mode
        virtualbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        virtualbox.name="SS-Attacker"
    end
    # Enable provisioning with a shell script.
    box.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y netwox telnet tshark
      apt-get autoremove -y
    SHELL

 end
end
